name: Build and Deploy

on:
  push:
    branches: ["main"]
  #pull_request:
  workflow_dispatch:

jobs:
  build-bicep:
    name: Build Bicep
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Login With OpenID Connect
      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - uses: azure/bicep-deploy@v2
        id: bicep-deploy
        with:
          type: deploymentStack
          operation: create
          name: Development
          location: australiaeast
          scope: resourceGroup
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID}}
          resource-group-name: rg-storage-web-australiaeast
          template-file: ./bicep/main.bicep
          parameters-file: ./bicep/parameters.json
          action-on-unmanage-resources: delete # Delete unmanaged resources
          deny-settings-mode: none # Allow write and delete operations

      - name: Get Storage Account connection string
        id: connection-string
        run: |
          echo "storageAccountKey=$(az storage account show-connection-string --name ${{ steps.bicep-deploy.outputs.storageAccountName }} --resource-group rg-storage-web-australiaeast -o tsv)" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: pnpm install
        run: pnpm install

      - name: pnpm build
        run: pnpm build

      - name: Azure Blob Storage Upload
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          connection_string: ${{ steps.connection-string.outputs.storageAccountKey }}
          container_name: "$web"
          source_dir: ./dist
          sync: true
